### ISSUE TITLE
`matmul` produces wrong results. 

### ISSUE THREAD

**Issue by wujingyue** [NVIDIA/Fuser#1701]
I vaguely remember MmaOp today has known limitations dealing with irregular sizes. Anyhow, such limitations should probably be hidden from the user-facing API -- whether it's the `matmul` function  in `test/utils.h` (the only API I'm aware of that generates MmaOp) or something we'll create in the future. 

```shell
git fetch origin wjy/matmul_wrong_result
git checkout wjy/matmul_wrong_result
_bn && bin/test_matmul --gtest_filter=*WrongResult*
```

For your convenience, I copied the reproducer from https://github.com/NVIDIA/Fuser/blob/wjy/matmul_wrong_result/test/test_matmul_scheduler.cpp to here:

```cpp
TEST_F(MatmulSchedulerTest, WrongResultOnSmallDimensionSizes) {
  constexpr int m = 2;
  constexpr int k = 3;
  constexpr int n = 5;

  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  TensorView* a = makeContigTensor(2, DataType::Half);
  fusion->addInput(a);
  TensorView* b = makeContigTensor(2, DataType::Half);
  fusion->addInput(b);

  TensorView* c = matmul(a, b, MmaLayout::TT, /*turing_or_later=*/true);
  c = castOp(DataType::Half, c);
  fusion->addOutput(c);

  FusionExecutorCache fec(std::move(fusion));

  auto options = at::TensorOptions().dtype(at::kHalf).device(at::kCUDA, 0);
  at::Tensor a_tensor = at::randn({m, n}, options);
  at::Tensor b_tensor = at::randn({n, k}, options);
  std::vector<at::Tensor> out_tensors =
      fec.runFusionWithInputs({a_tensor, b_tensor});
  testValidate(
      fec.fusion(),
      out_tensors,
      {a_tensor, b_tensor},
      {a_tensor.matmul(b_tensor)},
      __LINE__,
      __FILE__);
}
```

**Comment by wujingyue** [comment]
cc both @protonu and @zasdfgbnm 

This probably falls onto @protonu 's plate of sorting out the matmul API, so I assigned it to you.

**Comment by zasdfgbnm** [comment]
@wujingyue Do you mind copy-pasting the failing test here? This would be easier to read.

I am not surprised that there could be a wrong result in matmul kernels. We are currently implicitly making many assumptions, for example, hardcode vectorization factor 8 (https://github.com/NVIDIA/Fuser/issues/983).

https://github.com/NVIDIA/Fuser/blob/0dd180a133a771a3b907a758d7bc7271f763dc2d/csrc/scheduler/matmul.cpp#L560-L567

I think there are two directions:
1. Make sure we do not use nvFuser generated kernel on these cases.
2. Fix the bug and make sure generated kernel works of these shapes.

2 is more difficult than 1. I think we should work on both direction, 1 for short term, 2 for long term. Currently, I don't think we have anyone working on 2, because all our matmul workers are fully loaded on other tasks.

CC more people for visibility: @drzejan2 @mmigdal-nv @naoyam @jacobhinkle

**Comment by wujingyue** [comment]
Unable to reproduce -- this has apparently been fixed.

**Comment by jacobhinkle** [comment]
> Unable to reproduce -- this has apparently been fixed.

Thanks for checking this again. I think this is probably working now because we have actual vectorization analysis in the matmul scheduler e.g. #2105. As @zasdfgbnm mentioned above, we previously assumed all operands and outputs are vectorizable with width 8, but that can lead to incorrect results if it is violated.
