### ISSUE TITLE
Codegen tensor to support arbitrary stride order

### ISSUE THREAD

**Issue by jjsjann123** [NVIDIA/Fuser#248]
## Background and Past Discussions

Linking old request from almost two years ago: https://github.com/csarofeen/pytorch/issues/1144

We want to extend the support to allow user to specify input stride order along with contiguity flag.
Something like:
```
  std::vector<std::optional<bool>> contiguity_;
  std::vector<std::optional<size_t>> stride_order_;
```

where user should be able to specify `stride_order_` on how input tensor is stored on memory. The reason to have an `optional` there is similar to how contiguity_ is handled, for broadcasting dimensions, stride_order and contiguity is meaningless and they should be clearly marked in the field.

e.g. 
    - input size `[N, C, H, W]` and stride `[C*H*W, H*W, W, 1]`, stride_order_ should be [3, 2, 1, 0]
    - input size `[N, C, H, W]` and stride `[H*W*C, 1, W*C, C]`, stride_order_ should be [3, 0, 2, 1]

## Motivation

Stride order is useful in different ways.

1. Matmul support! cc'ing @zasdfgbnm 

Right now we have to change the semantic meaning of the dimensions in order to handle different matmul configuration: https://github.com/NVIDIA/Fuser/blob/ff845e8bd882681f17ab9ffb8b6d2f765c60bed5/test/utils.cpp#L286-L319

2. Explicit control on output tensor memory format. 

We can support stride order explicitly marked on our output. https://github.com/NVIDIA/Fuser/blob/ff845e8bd882681f17ab9ffb8b6d2f765c60bed5/csrc/python_frontend/python_bindings.cpp#L332-L335
Linking the ancient feature request: https://github.com/csarofeen/pytorch/issues/1601

Note that the request on output has been handled by leveraging permutation support from our cpp integration: https://github.com/csarofeen/pytorch/pull/2548
^^^ This is really messy and we'd prefer that we don't have to do this on the integration.

3. Allows dimension collapsing on permuted contiguous tensor.

This is especially useful on point-wise kernels for permuted inputs, like NHWC support. Currently we don't have it supported via our python API.

### how do we expose this to user

stride_order and contiguity is confusing and tied to implementation-specific details of codegen. In the meantime, stride_order and contiguity can be vague as there's no good way to disambiguate it with size and stride (https://github.com/pytorch/pytorch/issues/24090).

We need to be careful with what we give at the API level. `stride_order` should be something that user can dictate (if they want to), otherwise, we can *try* to infer it from existing `size` and `stride`, or just assume descending strides when there's not enough information provided.
Meanwhile, `contiguity_` shouldn't really be messed with by the user. Having said that, we do want to expose util functions to compute those in case user/integration wanted to have higher level caching system. Similar to how we are currently exposing: https://github.com/NVIDIA/Fuser/blob/main/csrc/python_frontend/python_bindings.cpp#L29-L71

### where do we store stride_order

How this should be implemented is up for backend devs. cc'ing @naoyam @zasdfgbnm who have been in the discussion here. My elevator pitch is that we should put this inside `TensorDomain` next to `contiguity_` flag, since `contiguity_` is only meaningful within the context of stride_order.

@naoyam suggested that we can keep `stride_order` out of codegen and only infer it from runtime information. We didn't cover that topic thorough enough in the meeting to come to any conclusion yet.
I'm uncertain if there's any clean way to support output permutation with that, since output is allocated from inference based on codegen IR.

**Comment by naoyam** [comment]
Is the stride order static? In other words, when we define a fusion, can we assume we know the stride order of all tensors?

**Comment by zasdfgbnm** [comment]
> Is the stride order static? In other words, when we define a fusion, can we assume we know the stride order of all tensors?

I think this is a matter of design of caching system. We can make it static, for example, make the stride order part of the key of the cache: if the stride order changed, then there is no cache hit, and we will get a new fusion. In this design, it makes sense to attach stride order as a field of `TensorView`, because this naturally implies that different stride order means different fusion.
 
On the other hand,  we can also make the stride order a field of the heuristics. In this case, the scheduler will get the same fusion, but it will generate different heuristics for different stride order, therefore leading to different schedule and different kernel. In this design, I don't think it make sense to attach stride order as a field of `TensorView`.

However, no matter how we design, what is unchanged is that different input/output stride order implies different kernel.

**Comment by jjsjann123** [comment]
^^^ very much agree to what Xiang mentioned above.

The proposal I made above implies that stride order being static and known at compile time. Hence the decision to push that inside `TensorView`

If we want to make this a dynamic thing, since we have `what is unchanged is that different input/output stride order implies different kernel.`, I think we'll inevitably have to fork different kernels at runtime. So the `stride_order`, along with `contiguity`, will be pushed to something similar to `concretization`.

I don't have a strong opinion on which is the *right* way to do this. I do think keeping it as a static thing makes life easier at least in the short run. Since it's closer to what we have with `contiguity` as well.

**Comment by naoyam** [comment]
> > Is the stride order static? In other words, when we define a fusion, can we assume we know the stride order of all tensors?
> 
> I think this is a matter of design of caching system. 

Yes, I'm wondering what the design of the user interface should look like. I think the "fusion" should just define what are computed but not how. It's not always clear what properties should be defined when computations are defined, but there are some reasonable assumptions we can make. For example, it'd be reasonable to think about such properties as tensor ranks and data types are part of compute definitions. I also think that it's reasonable to say contiguity is not part of compute definitions but rather how computations should be done.

This distinction is important because 

> However, no matter how we design, what is unchanged is that different input/output stride order implies different kernel.

This is highly likely the case but not always. It's just up to how we schedule user-defined computations. It is possible that in some cases some part of the differences of stride orders may not affect performance much, then we might want to just generate one kernel. For example, the order of outer-most dimensions may not matter if they are mapped to `blockIdx`. 

In this sense, the current `contiguity_` field of `TensorView` isn't ideal. It doesn't define what computations are done but jut how. For example, if there's no merge domain and no vectorization, both of them are scheduling decisions, the `contiguity_` flags don't affect anything in generated kernels, but still we end up having unique kernels for different `contiguity_` patterns as its part of fusion definitions.

And I guess this is why I'm feeling a little reluctant to have the stride order as part of `TensorView`. I'm not saying we should never do so, but I'd be fine if could make more sense from, say, engineering perspectives.

**Comment by jjsjann123** [comment]
Those are fair questions! I think we should discuss those and have some rough ideas on what codegen API should be in the long-term and work towards that.

> I'd be fine if it could make more sense from, say, engineering perspectives.

This sounds a lot more actionable at the same time. II wasn't doing a good job comparing different approaches on how they would affect schedulers/executors. @zasdfgbnm just walked through some examples and ideals with me, I'll think about that and write down more concrete bullet points comparing our alternatives.

**Comment by zasdfgbnm** [comment]
Just did an offline discussion with @jjsjann123. I will let @jjsjann123 post comparison of different approaches, and the benefit of his proposal. I think the benefit is mostly on the readability/debugability of fusion IR from the user's perspective, and the code cleanliness on the integration part.

I am not sure if I agree with
> I think the "fusion" should just define what are computed but not how.
and
> I also think that it's reasonable to say contiguity is not part of compute definitions but rather how computations should be done.
I need to think more about it. But what I am sure is I am at least neither strongly against it nor strongly agree with it. Which design sounds more "natural" is hard, and I need to think more about whether to vote for a weak yes or weak no.

Here, I will mostly be focusing on what that means for codegen in terms of engineering assume @jjsjann123's suggestion was taken. I want to bring everything (good or bad) on the table so that we can discussion what decision we want to make. @naoyam Feel free to add more if I am missing something.

**1. Definition of transpose**

I think the biggest change should be our mindset about the concept "transpose". In the past, the concept of transpose was simple: it is just a `TransposeOp`. After https://github.com/NVIDIA/Fuser/pull/148, and with my idea about "implicit transpose" in https://github.com/NVIDIA/Fuser/issues/203, the concept of transpose is not as obvious any more because in the tensor op level, it is just an arbitrary op. For example, `T1 = sin(T0)`, this sin can have a transpose if and only if "the order in T1's rFactor domain is different from T1's root domain", but if @jjsjann123's suggestion is taken, then the definition of transpose will change into "the stride order of T1's (maybe) rFactor domain is different from the stride order of T0's (maybe) rFactor domain". For example:

This does not have a transpose:
```
T1 = sin(T0)

T0:
root domain: [I0, I1]
stride order: [I1, I0]

T1:
root domain: [I0, I1]
rFactor domain:  [I1, I0]
stride order: [I1, I0]
```

This does have a transpose:
```
T1 = sin(T0)

T0:
root domain: [I0, I1]
stride order: [I1, I0]

T1:
root domain: [I0, I1]
stride order: [I0, I1]
```

I think we should have a `ir_utils::hasTranspose` to encapsulate this concept.

And this change can means a lot for schedulers, because a plain old `set` that just copy the root domain of the producer into consumer may no longer be a `set` but indeed a transpose now.

**2. Pointwise scheduler/Transpose scheduler**

Currently, the segmenter dispatch between pointwise and transpose scheduler base on whether all input and output tensors' `getMaybeRFactorDomain().at(-1)` match with each other. If the match, then pointwise scheduler will be chosen, otherwise, transpose scheduler will be chosen. It doesn't matter if there is a transpose op in the fusion or not.

If @jjsjann123's suggestion is taken, these two schedulers will still functionally working and schedule a kernel that compute the correct result without any change. And for the case where the stride order is indeed ascending, I don't think there will be any change in the performance of the generated kernel.

However, for the case where the stride order is not ascending, the dispatch between pointwise and transpose scheduler will be wrong. For example, for the `T1[4096, 8192] = set(T0[4096, 8192])` fusion, it will always be dispatched to the pointwise scheduler, although if T0's stride order is `[4096, 8192]` and T1's stride order is `[8192, 4096]`, transpose scheduler is a better choice.

I think fixing this behavior will be most mechanical changes, mostly changing `.at(i)` into `.at(stride_order.at(i))`.

**2. Reduction scheduler/Persistent scheduler**

I am not very familiar with these two schedulers. My understanding is, for ascending stride order, there will be no change, and for non-ascending stride order, the scheduler will not be able to tell inner/outer reduction correctly. And the change should also be almost mechanical. Currently, we do not support transpose-reduction fusion well, but I believe this is not related to this topic. As long as we are clear about the definition of "is transpose", I think @jjsjann123's suggestion does not make the support of transpose-reduction fusion easier or harder, not more or less important.

**3. Matmul scheduler**

I think it is mostly related to finding the correct matmul layout, and to do matmul-transpose fusion. Again, my opinion is, as long as we are clear about the definition of "is transpose", I think @jjsjann123's suggestion does not make this task easier or harder. But I do hope that we can make decision early, so that I can take this into consideration early, instead of finishing a task then do extra work to change it.

**4. Lowering**

I think the biggest impact for lowering is the change of semantics of contiguity. Now contiguity no longer means if it is contiguous to the next dim, but to the next dim in stride order. I think changing this will be slightly larger amount of work than https://github.com/csarofeen/pytorch/pull/2517. The change is mostly mechanical, but will not be trival. There do exist some points that require carefully thinking. And I think it is easy to introduce a new bug to lowering during this change, because most of our unit tests are using the ascending stride order, and it is very easy to mistakenly using the old semantics of contiguity somewhere, but not being catched by a unit test.

**Comment by naoyam** [comment]
> This does not have a transpose:
> 
> ```
> T1 = sin(T0)
> 
> T0:
> root domain: [I0, I1]
> stride order: [I1, I0]
> 
> T1:
> root domain: [I0, I1]
> rFactor domain:  [I1, I0]
> stride order: [I1, I0]
> ```
> 
> This does have a transpose:
> 
> ```
> T1 = sin(T0)
> 
> T0:
> root domain: [I0, I1]
> stride order: [I1, I0]
> 
> T1:
> root domain: [I0, I1]
> stride order: [I0, I1]
> ```
> 

Sounds like it's mixing the mathematical concept of transpose and memory formats. The first case does have a matrix transposition, whereas the second has a memory format change but not matrix transposition.

What I'm advocating is we should be able to describe mathematical transpose in Fusion, but I'm not sure memory formats should be part of fusion definitions.

**Comment by jjsjann123** [comment]
Lol using the word `transpose` here is confusing. Let's not do that. Yes, transpose should be a strict `semantic` operation that does not necessarily needs to realize `stirde_order` updates. Let's stick with that and not mix it up with the `stride_order` that we are trying to model here.

> What I'm advocating is we should be able to describe mathematical transpose in Fusion, but I'm not sure memory formats should be part of fusion definitions.

I agree with the first part. In the meantime, I think it's important memory formats or `stride_order` can be described for IO tensors. Otherwise, we are just leaving a lot of the perf on the table (or being handled by integration... which is still leaving opportunities of optimization out side of codegen).

**Two things I think our codegen API should support:**
1. user should be able to tell us the `stride_order` on input tensors and we should be able to leverage contiguity on arbitrary `stride_order`;
2. user should be able to request output in a specific `stride_order`

^^^ I think we do agree on this part.

Meanwhile, what we don't agree on is how far should we extend this support to the backends. I think what @zasdfgbnm was advocating isn't limited to what frontend is passing to codegen, but rather how codegen can refactor the inwards to leverage that information.

**I do think this requires us to have `stride_order` exposed in the codegen definition, given that we already have `contiguity_` flag in TensorDomain at this point. However, I'm very open minded if we decide to refactor even how `contiguity_` is handled.**

**Comment by zasdfgbnm** [comment]
> Lol using the word `transpose` here is confusing. Let's not do that.

I think for scheduling, the most important concept is "whether the memory format has changed", not "whether the semantics meaning of tensor dimensions has changed", we can of course avoid using the word "transpose", but we should at least invent a new word with exactly the same meaning to replace "transpose" and speak that new word in the context of codegen. I agree this is strange, and I think this strangeness is:
1. unavoidable if we do want to handle stride order in codegen.
2. the biggest reason why I don't like stride order to be in codegen.

**Comment by jjsjann123** [comment]
For a simple program below, showing that we would want to be able to express arbitrary stride_order on both inputs (along with leveraging contiguity) and outputs to codegen.

```
  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({3, 6, 7}, options).transpose(-1, -2);
  at::Tensor t1 = at::randn({1, 6, 7}, options);

  auto tv0 = TensorViewBuilder()
                 .ndims(3)
                 .contiguity({false, false, false}) // We are not able to feed contiguity flag of a tensor with arbitrary stride_order to codegen
                 .shape({-1, -1, -1})
                 .dtype(DataType::Float)
                 .build();
  auto tv1 = TensorViewBuilder()
                 .ndims(3)
                 .contiguity({c10::nullopt, true, true})
                 .shape({1, -1, -1})
                 .dtype(DataType::Float)
                 .build();

  fusion->addInput(tv0);
  fusion->addInput(tv1);
  auto transposed_tv1 = transpose(tv1, -1, -2);

  auto tv2 = add(tv0, transposed_tv1);

  fusion->addOutput(tv2); // We can not dictate stride_order on output tensor neither.
```
The math ir looks pretty simple
```
Inputs:
  T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ], float
  T1_g[ bS3{1}, iS4{i5}, iS5{i6} ], float
Outputs:
  T3_g[ iS9{i0}, iS10{i1}, iS11{i2} ], float

%kernel_math {
T2_l[ bS6{1}, iS8{i6}, iS7{i5} ]
   = Set.Permute( T1_g[ bS3{1}, iS4{i5}, iS5{i6} ] )
T3_g[ iS9{i0}, iS10{i1}, iS11{i2} ]
   = T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ]
   + T2_l[ bS6{1}, iS8{i6}, iS7{i5} ];
}
```
Currently the thing generated a kernel like:
```
__global__ void kernel1(Tensor<float, 3> T0, Tensor<float, 3> T1, Tensor<float, 3> T3) {
  int i1128;
  i1128 = ((nvfuser_index_t)threadIdx.x) + (128 * ((nvfuser_index_t)blockIdx.x));
  int i1129;
  i1129 = T0.size[1] * T0.size[2];
  int i1130;
  i1130 = i1128 % i1129;
  int i2939;
  i2939 = i1130 / T0.size[2];
  int i1131;
  i1131 = i1130 % T0.size[2];
  int i8531;
  i8531 = (T0.size[0] * T0.size[1]) * T0.size[2];
  if ((((((nvfuser_index_t)blockIdx.x) < (ceilDiv(i8531, 128))) && (i1130 < i1129)) && (i1128 < i8531))) {
    float T5[1];
    T5[0] = 0;
    T5[0]
       = T1[((T0.size[1] * i1131) + i2939)];
    float T4[1];
    T4[0] = 0;
    T4[0]
       = T0[(((T0.stride[0] * (i1128 / i1129)) + (T0.stride[1] * i2939)) + (T0.stride[2] * i1131))];
    float T2[1];
    T2[0]
       = T5[0];
    float T6[1];
    T6[0]
      = T4[0]
      + T2[0];
    T3[i1128]
       = T6[0];
  }
}
```

If we look at `T4[0] = T0[(((T0.stride[0] * (i1128 / i1129)) + (T0.stride[1] * i2939)) + (T0.stride[2] * i1131))];`, unsurprisingly we are not leveraging the packed memory of T0 and the indexing is not collapsed.
Output here is also fixed to be in an monotonic ascending stride order.

Here's our two alternatives:
1. support in integration/runtime.
What we can do is that we can have runtime to support `stride_order` on input/output:

- For an input tensor with an arbitrary stride order: i. in order to mark contiguity correctly to codegen, we can permute the tensor to have it in an ascending stride order before passing it to codegen; ii. in order to preserve correct semantics, we need to immediately add a permute op on the input tensor to restore the semantic dimensions.

- Similarly for an output tensor where we want to dictate an output stride order, we can do so by: i. adding a permutation on the output tensor; ii. after retrieving the output tensor, we'll permute it to restore correct semantics.

If we want to work on the example above, code changes looks like this
```
   auto tv0 = TensorViewBuilder()
                  .ndims(3)
-                 .contiguity({false, false, false}) // ttfff
+                 .contiguity({true, true, true})
                  .shape({-1, -1, -1})
                  .dtype(DataType::Float)
                  .build();
@@ -8297,12 +8297,16 @@ TEST_F(NVFuserTest, FusionContigStrideOrder_CUDA) {
                  .build();

   fusion->addInput(tv0);
+  fusion->setPermutationOnInput(0, {0, 2, 1});
+  auto transposed_tv0 = transpose(tv0, -1, -2);
   fusion->addInput(tv1);
   auto transposed_tv1 = transpose(tv1, -1, -2);

-  auto tv2 = add(tv0, transposed_tv1);
+  auto tv2 = add(transposed_tv0, transposed_tv1);
+  auto transposed_tv2 = transpose(tv2, 0, 2);

-  fusion->addOutput(tv2);
+  fusion->addOutput(transposed_tv2);
+  fusion->setPermutationOnOutput(0, {2, 1, 0});
```

The generated kernel index into the permuted T0 as `T6[0] = T0[((((T0.size[2] * T0.size[1]) * (i2805 % T0.size[0])) + i1106) + i2806)];` Notice how this is leveraging the contiguity properties.

Here's the fusion IR (vvv). I want to point out that there's also transpose/permutation on input `t0` and output `codegen_outputs[0]`, which is not reflected in the codegen IR below. (it's done via `Fusion::setPermutationOnInput/Output`)
```
Inputs:
  T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ], float
  T1_g[ bS3{1}, iS4{i5}, iS5{i6} ], float
Outputs:
  T5_g[ iS17{i1}, iS16{i2}, iS15{i0} ], float

%kernel_math {
T2_l[ iS6{i0}, iS8{i2}, iS7{i1} ]
   = Set.Permute( T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ] )
T3_l[ bS9{1}, iS11{i6}, iS10{i5} ]
   = Set.Permute( T1_g[ bS3{1}, iS4{i5}, iS5{i6} ] )
T4_l[ iS12{i0}, iS13{i2}, iS14{i1} ]
   = T2_l[ iS6{i0}, iS8{i2}, iS7{i1} ]
   + T3_l[ bS9{1}, iS11{i6}, iS10{i5} ];
T5_g[ iS17{i1}, iS16{i2}, iS15{i0} ]
   = Set.Permute( T4_l[ iS12{i0}, iS13{i2}, iS14{i1} ] )
}
```

2. support in codegen.

The proposed codegen refactor is to allow `TensorDomain` to specify `stride_order` directly. A mock up IR is that, we'll change it to something like
```
  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({3, 6, 7}, options).transpose(-1, -2);
  at::Tensor t1 = at::randn({1, 6, 7}, options);

  auto tv0 = TensorViewBuilder()
                 .ndims(3)
                 .contiguity({true, true, true}) // we can now set everything as contiguous
                 .stride_order({0, 2, 1}) // this is important, since the input is only contiguous per the stride_order
                 .shape({-1, -1, -1})
                 .dtype(DataType::Float)
                 .build();
  auto tv1 = TensorViewBuilder()
                 .ndims(3)
                 .contiguity({c10::nullopt, true, true})
                 .stride_order({c10::nullops, 0, 1}) // note that stride_order here could be omitted.
                 .shape({1, -1, -1})
                 .dtype(DataType::Float)
                 .build();

  fusion->addInput(tv0);
  fusion->addInput(tv1);
  auto transposed_tv1 = transpose(tv1, -1, -2); // transpose should still be needed here to keep the graph semantically correct

  auto tv2 = add(tv0, transposed_tv1);

  fusion->addOutput(tv2, {2, 1, 0}); // We can annotate stride_order on output tensor as well.
```

Since we didn't change any computational definition here, the math ir should look identical to the original graph
```
Inputs:
  T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ], float
  T1_g[ bS3{1}, iS4{i5}, iS5{i6} ], float
Outputs:
  T3_g[ iS9{i0}, iS10{i1}, iS11{i2} ], float

%kernel_math {
T2_l[ bS6{1}, iS8{i6}, iS7{i5} ]
   = Set.Permute( T1_g[ bS3{1}, iS4{i5}, iS5{i6} ] )
T3_g[ iS9{i0}, iS10{i1}, iS11{i2} ]
   = T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ]
   + T2_l[ bS6{1}, iS8{i6}, iS7{i5} ];
}
```

Even with today, the transformed kernel should look something like this:
```
%kernel {
T4_l[ iblockIdx.x67{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( i1 * i2 ) ), 128) ), 1) ), 1) )}, iUS68{1}, iS66{1}, ithreadIdx.x64{128} ] ca_pos( 2 )
   = Set( T0_g[ iS75{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( i1 * i2 ) ), 128) ), 1) ), 1) )}, iS76{1}, iS74{1}, iS72{128} ] )
T5_l[ iblockIdx.x51{( ceilDiv(( ceilDiv(( ceilDiv(( 1 * ( i6 * i5 ) ), 128) ), 1) ), 1) )}, iUS52{1}, iS50{1}, ithreadIdx.x48{128} ] ca_pos( 2 )
   = Set( T1_g[ iS59{( ceilDiv(( ceilDiv(( ceilDiv(( 1 * ( i6 * i5 ) ), 128) ), 1) ), 1) )}, iS60{1}, iS58{1}, iS56{128} ] )
T2_l[ iblockIdx.x43{( ceilDiv(( ceilDiv(( ceilDiv(( 1 * ( i6 * i5 ) ), 128) ), 1) ), 1) )}, iUS44{1}, iS42{1}, ithreadIdx.x40{128} ] ca_pos( 4 ) produce_pos( 2 )
   = Set.Permute( T5_l[ iblockIdx.x51{( ceilDiv(( ceilDiv(( ceilDiv(( 1 * ( i6 * i5 ) ), 128) ), 1) ), 1) )}, iUS52{1}, iS50{1}, ithreadIdx.x48{128} ] ca_pos( 2 ) )
T6_l[ iblockIdx.x35{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( i1 * i2 ) ), 128) ), 1) ), 1) )}, iUS36{1}, iS34{1}, ithreadIdx.x32{128} ] ca_pos( 4 ) produce_pos( 4 )
   = T4_l[ iblockIdx.x67{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( i1 * i2 ) ), 128) ), 1) ), 1) )}, iUS68{1}, iS66{1}, ithreadIdx.x64{128} ] ca_pos( 2 )
   + T2_l[ iblockIdx.x43{( ceilDiv(( ceilDiv(( ceilDiv(( 1 * ( i6 * i5 ) ), 128) ), 1) ), 1) )}, iUS44{1}, iS42{1}, ithreadIdx.x40{128} ] ca_pos( 4 ) produce_pos( 2 );
T3_g[ iblockIdx.x27{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( i1 * i2 ) ), 128) ), 1) ), 1) )}, iUS28{1}, iS26{1}, ithreadIdx.x24{128} ] ca_pos( 2 ) produce_pos( 4 )
   = Set( T6_l[ iblockIdx.x35{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( i1 * i2 ) ), 128) ), 1) ), 1) )}, iUS36{1}, iS34{1}, ithreadIdx.x32{128} ] ca_pos( 4 ) produce_pos( 4 ) )
```

If we only look at the input with a non-trivial stride-order `T0_g` and the loaded tensor `T4_l`, we should see it as something like this:
```
T0_g[]:
  root domain : (iS0{i0}, iS1{i1}, iS2{i2})
  contiguity: t t t
  stride_order: 0, 2, 1
T4_l[]:
  root domain: (iS0{i0}, iS1{i1}, iS2{i2})
  contiguity: t t t
  stride_order: 0, 1, 2
```

`stride_order` would only be associated with global tensors. `stride_order` is only applicable on `root domain`. It gives us a clear distinction between permutation, which manifests as an rfactor transform that affects semantics.
When we actually inline those, we should be able to figure out consistent stride_order from inputs to outputs and cancel out those permutation. (I should probably get a better example there).

With matmul (@zasdfgbnm might have a better explanation on this one):
The stride_order associated with T0_g[] gives an explicit hint on the input stride_order. In the sense of matmul, we should be able to use that to figure out which actual load pattern we would want to use. (I don't think it actually works well right now since we are very explicit about matmul permuting tensors to WAR the lack of representation of `stride_order`).

**Comment by zasdfgbnm** [comment]
Assign myself to add stride-order support to codegen.

**Comment by jjsjann123** [comment]
closing since we have allocation domain now.
