### ISSUE TITLE
Indexing error in matmul with certain parameters

### ISSUE THREAD

**Issue by jacobhinkle** [NVIDIA/Fuser#2763]
Modifying the `AmpereMatmul` test in `test_matmul.cpp` to the following:
```diff
 
   MatMulTileOptions gemm_tile;
-  gemm_tile.cta_tile = GemmTile(128, 128, 32);
+  gemm_tile.cta_tile = GemmTile(64, 64, 32);
   gemm_tile.warp_tile = GemmTile(64, 64, 32);
   gemm_tile.instruction_tile = GemmTile(16, 8, 16);
 
   MatmulParams params;
   params.supported_vec_size = {8, 8, 4};
   params.mma_macro = MmaMacro::Ampere_16_8_16;
   params.tile_sizes = gemm_tile;
   params.async_gmem_load_operands = true;
   params.circular_buffer_options.circular_buffer_smem_write = true;
   params.circular_buffer_options.circular_buffer_smem_read = true;
   params.circular_buffer_options.smem_circular_buffer_stage = 4;
+  params.use_smem_epilogue = true;
   scheduleMatmul(&fusion, params);
```
results in this error:
> C++ exception with description "loop_index->isZeroInt() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/id_model/indexing.cpp":848, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Unexpected initial index: threadIdx.y
Exception raised from getInitialIndexMap at /opt/pytorch/nvfuser/csrc/id_model/indexing.cpp:848 (most recent call first):

**Comment by jacobhinkle** [comment]
Git bisect shows this bug was introduced in #2669

**Comment by zasdfgbnm** [comment]
Finally get some time to look at this... I think the problem is: if I have an IterDomain of size 1, and I parallelize this on `TIDy`, should the index be `0`, or `threadIdx.y`? Both are correct as `threadIdx.y` is always zero, but tensor indexing currently is checking that it is zero. Just commenting out the failed check will make it work, but I believe actually making it `0` is better than `threadIdx.y` because `0` will enable more optimization opportunity on nvcc.
