### ISSUE TITLE
Python test "at-exit" serialization has effect on repeat testing runs

### ISSUE THREAD

**Issue by jacobhinkle** [NVIDIA/Fuser#3265]
Recently we noticed that codediff in CI was showing diffs for branches that had trivial changes. The reason turned out to be that running the python tests a second time on the same machine can give slightly different results. This is because of the default saving of FusionCache to a temporary file upon program exit. This is documented here:
https://github.com/NVIDIA/Fuser/blob/85c22a2af3fc756d9b301c93ac29b2bba8abf2af/tests/python/utils.py#L275-L287

When the test is run a second time, the serialized FusionCache is loaded, after which some FusionDefinitions will become cache hits whereas they were cache misses on the first invocation of the test suite. I worked around this by just backing up the fusion cache and restoring it in #3260, but setting `DEBUG_SERDE=true` is an alternative.

I have not observed this yet but I am slightly worried that we might hit this during development. If we are making changes to the backend and we're running a python test repeatedly, is it possible that we will load the stale version of the fusion instead of the new one? Is `DEBUG_SERDE` the best interface: should we rename it, or add this as a pytest cmdline arg? Also, it's important to test this functionality which is fundamental to serde, but should we disable it by default and enable it only for the CI jobs? I'm opening this issue for discussion. cc @rdspring1

**Comment by rdspring1** [comment]
For active development on your local machine, there isn't much to do beyond `rm -rf /tmp/nvfuser_kernel_db` to completely clear state or to remember to use `DEBUG_SERDE` flag.

Any issues should be caught on the CI because we run the serialization tests twice. Once with a clean cache and a second time with the saved cache.

We clear the state automatically when we cannot deserialize or there is a version mismatch. Under active development, you may forget to update the version, so you get a stale state.

**Comment by naoyam** [comment]
Should it be off by default? Assuming normal use case of the tests are not for testing serde itself, it seems to make more sense if it's off by default.
