### ISSUE TITLE
Remove redundant type casts

### ISSUE THREAD

**Issue by liqiangxl** [NVIDIA/Fuser#342]
redundant type casts in FP16 Layer Norm with fused ops lead to additional persistent buffers and reduced performance.
https://github.com/NVIDIA/Fuser/issues/335

Per offline discussion, tasks:
- [x] start a PR that cleans up cascading casts during lowering #355 
- [ ] investigating where duplicated casts are inserted on frontend

**Comment by jjsjann123** [comment]
One place inside nvfuser where consecutive casts surprisingly shows up is where the fusion definition tries to do half precision math.

Due to the lack of support on operations on half, we ended up needing to cast dtype back to float for those operations and casting them back to half.

**Comment by jjsjann123** [comment]
FYI, #355 will no longer fix this issue for us, since the cast op in the example isn't safe to be removed (numerical impacts). See discussion in the PR for details.  https://github.com/NVIDIA/Fuser/pull/355#discussion_r1202918774

I'll peek into the script to see where the cast to half is inserted and hopefully fix that instead for the short term patch.

**Comment by liqiangxl** [comment]
since #355 removes redundant casts, we don't need to investigate where duplicated casts are inserted on frontend or it is not a task of nvFuser.
