### ISSUE TITLE
Feature: allow explicit manipulation of Philox RNG state via functional version of RNG ops

### ISSUE THREAD

**Issue by IvanYashchuk** [NVIDIA/Fuser#535]
The request is to implement
```cpp
TensorView functional_uniform(Val* philox_seed, Val* philox_offset, const std::vector<Val*>& shape,  Val* low,  Val* high, DataType dtype)
```
and the corresponding Python bindings. This operation should *not* increase nvFuser's `rand_offset` defined here https://github.com/NVIDIA/Fuser/blob/730215f36f679867ef25b56bd68dae17d13037f9/csrc/executor.cpp#L1460-L1468
because it's essentially a deterministic operation.

In addition, the result should be independent of the chosen vectorization, but I think it is already implemented by using linear index here
https://github.com/NVIDIA/Fuser/blob/730215f36f679867ef25b56bd68dae17d13037f9/csrc/codegen.cpp#L706

**Motivation**
Currently, nvFuser has two random ops `uniform` and `normal`. Internally it uses a Philox PRNG and its state is tied to PyTorch's RNG state. For each kernel invocation nvFuser is advancing PyTorch's RNG by the number of random ops in a kernel:
https://github.com/NVIDIA/Fuser/blob/730215f36f679867ef25b56bd68dae17d13037f9/csrc/executor_kernel_arg.cpp#L603-L614

That offers a great eager-like experience and `torch.manual_seed` and `torch.random.fork_rng` behaves as expected with nvFuser kernel invocations.

However, there are cases where explicit seed manipulation might be more efficient, for example, for dropout backward it's sufficient to save the Philox seed to recompute the dropout mask during backward instead of saving the mask from forward.

**Comment by zasdfgbnm** [comment]
Interesting. In my TMA support, I am thinking about extending the codegen with the following:
1. A `kir::Kernel` could have `inputs` and `kernel_inputs`, where `inputs` are the one users provide, and `kernel_inputs` can have the same `Val*` as `inputs`, or it can have some different `Val*` which can be computed from the `Val*`s in `inputs`. This relationship between `inputs` and `kernel_inputs` is just like root domain and rFactor domain.
2. Lowering should be able to freely set `kernel_inputs`, but it can not modify `inputs`.
3. On the executor side, after binding inputs, it should be able to evaluate all `kernel_inputs` which is not in `inputs`.

I think this structure fits with this RNG needs well. When defining an RNG op using this functional interface, the user should have already added philox seed and offset as inputs. And when defining an RNG op without providing the philox seed and offset, during lowering, we can add two additional `Val*`s into `kernel_inputs` whose `definition()` is just a nullary `Expr` type,`GetPhiloxSeedAndOffsetFromATen`, and when fusion executor see this expr, it will evaluate this expr and get the seed and offset from ATen.

This framework will also allow us to do optimizations like, for example, when see a `tensor / scalar`, we can ask `kernel_inputs` to precompute `inv = 1 / scalar`, so that in kernel, we can be doing `tensor * inv` which could be faster.
