### ISSUE TITLE
Make matmul scheduler allocation-domain aware

### ISSUE THREAD

**Issue by zasdfgbnm** [NVIDIA/Fuser#977]
Currently, in `scheduleMatmul`, we are doing our analysis based on rFactor domain. For example, when there is a transpose, it will convert his transpose as a `ldmatrix.trans`. However, this behavior is not compatible with our long term design, which uses allocation domain to dictate allocation, and root/rfactor domain for semantics. So we should really be checking if there is a change in allocation, instead of checking the semantics. For example, if you have a PyTorch tensor `A` whose shape is `[K, M]` and whose stride is `[1, K]`, and another PyTorch tensor `B` whose shape is `[K, N]` and stride `[N, 1]`, and you do `A.T @ B`, then this should be treated as "no transposes" (`MmaLayout::TT`)

**Comment by zasdfgbnm** [comment]
This issue belongs to the mega-issue https://github.com/NVIDIA/Fuser/issues/984

**Comment by protonu** [comment]
![image](https://github.com/NVIDIA/Fuser/assets/10635897/5c166046-bf7e-46ca-91e0-4ff6d3e2f45d)






In this discussion when we say the matmul scheduler, we’ll mean the [scheduleMatmul function.](https://github.com/NVIDIA/Fuser/blob/d214286b2e75f59abeba03d5a06ce9fdb93ddc0d/csrc/scheduler/matmul.cpp#L739)

We will also assume that the implementation of the above is tied to the Matmul and Linear Op recently developed. In this note, we’ll focus on the matmul op. 

As shown in the figure above, we will convert the matmul op, which takes in inputs A and B with root domains [M, K] and [M, K] respectively, to a collection of transpose, broadcasts and Mma ops. Please note that the inputs A and B can both have allocation domains (transposed memory layouts - we do not place restrictions on that).

The task at hand focuses on how this collection of ops is handled in the scheduleMatmul function when the inputs have allocation domains. The table below outlines the configuration of inputs A and B we want to support.


<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-87592f69-7fff-92c4-e002-f34db17ce287"><div dir="ltr" style="margin-left:0pt;" align="center">
Root Domain A | Root Domain B | Allocation Domain A | Allocation Domain B
-- | -- | -- | --
[M, K] | [K, N] | [] | []
[M, K] | [K, N] | [] | [N, K]
[M, K] | [K, N] | [K, M] | []
[M, K] | [K, N] | [K, M] | [N, K]

</div></b>


The cases have been coded in these tests:
https://github.com/NVIDIA/Fuser/commit/493b4b7a4f0988733c36890722160a835a718641

Discussion with @jacobhinkle  and @zasdfgbnm led us to identifying the following issues to get the above cases running:

- Propagate allocation domain from gmem operands to their smem consumers.
   This was solved by Xiang a while back in commit [PR]. 
   (https://github.com/NVIDIA/Fuser/commit/626a405272263978c86f7c4f7d9898d14f494cf4).
- Update mma_utils::orderTiledConcreteIdAsRoot to use allocation domain instead of root.
- Detect transpose properly in scheduleLdMatrix
   This refers to the bit of code [here.](https://github.com/NVIDIA/Fuser/blob/d214286b2e75f59abeba03d5a06ce9fdb93ddc0d/csrc/scheduler/matmul.cpp#L893-L912)
We have to modify how we set LdMatrix vs. LdMatrix based not only on the comparison between rfactorDomain and root domain, but also takes into account the allocation domains of both shared memory or A and B. What I took this to mean is, for the shared memory TV of B, bcw_smem, since it's transposed, we will compare it's rfactor domain and alloction domain or the root domain (if allocation domain isn't there) to decide whether to transpose. And for input A, acw_smem, we'll compare the allocation domain and the root domain to see if we need to transpose. Please correct me if I have this wrong. 
- Update inline_ptx.cpp to detect when to append .trans instead of using a different LoadStoreOpType (optional)
@jacobhinkle  also pointed out that optionally, we may get rid of the enum LdMatrix/LdMatrixTrans and handle the transpose when lowering. 

In this draft PR, I prototyped the steps mentioned in the first three bullets above. 
https://github.com/NVIDIA/Fuser/pull/2226. The code there is able to handle all the cases mentioned in the table above.
If it sounds like a reasonable plan, I could clean up that code in the PR, and then later handle LdMatrix/LdMatrixTrans.

**Comment by protonu** [comment]
We have also had discussion regarding checks in the matmulscheduler based on the layout flag in the Mma op. 
Many thanks to @zasdfgbnm  who has sent a PR to remove that flag and check https://github.com/NVIDIA/Fuser/pull/2227. I think this should take care of our discussion around this topic - please let me know if I am wrong.

**Comment by protonu** [comment]
Furthermore, currently, When inputs A and B have root domains [M, K] and [K, N] respectively, we transpose B before scheduleMatmul function is invoked. I don't think it'll be a big change for the matmulSchedule function to successfully handle the four cases in the table above even when B is not transposed. I haven't tried it yet, but might spend some time on it. This may not be required right now, since we control the conversion of the matmul op.

**Comment by jacobhinkle** [comment]
Thanks @protonu. The drawing is helpful and this info matches my understanding.

> If it sounds like a reasonable plan, I could clean up that code in the PR, and then later handle LdMatrix/LdMatrixTrans.

That sounds reasonable to me. We can remove `LoadStoreOpType::LdMatrixTranspose` in a later cleanup (we would leave `LoadStoreOpType::LdMatrix` and infer whether it should be translated to `ldmatrix.*.trans` in `inline_ptx.cpp`.

**Comment by zasdfgbnm** [comment]
done
